### ISSUE TITLE
Okay, 'Alien'

### ISSUE THREAD

**Issue by theiocoder** [iop3/iop3.is-a.dev#2]
![literally](https://user-images.githubusercontent.com/64909897/122047499-3b6dfe80-cdae-11eb-8cae-eff3bd84593e.png)
![watcha gonna do when they comin for you](https://user-images.githubusercontent.com/64909897/122048333-1c23a100-cdaf-11eb-8ea2-f1b921ca874a.png)
> watcha gonna do when they come for you

**Comment by iop3** [comment]
HAHAHAHAHAHHAHAHHAHA XD
